/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expoferia.pagos.gestionpagos.gui;

import expoferia.pagos.gestionpagos.entidades.Empleado;
import java.awt.CardLayout;
import expoferia.pagos.gestionpagos.gui.panelcambiante.PanelEmpleado;
import expoferia.pagos.gestionpagos.gui.panelcambiante.*;

/**
 *
 * @author Suglin
 */
public class HomeAdmin extends javax.swing.JFrame {

    private CardLayout card;
    private Empleado empleado;

    public HomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelLateral = new javax.swing.JPanel();
        pagoButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tipoPagoButton = new javax.swing.JButton();
        estudianteButton = new javax.swing.JButton();
        represanteButton = new javax.swing.JButton();
        empleadoButton = new javax.swing.JButton();
        administradorButton = new javax.swing.JButton();
        panelCambiante = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(204, 204, 204));

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        panelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 72, 162));
        jLabel3.setText("SISTEMA DE PAGOS COLEGIO GONZAGA");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bars.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoSuperiorCole.png"))); // NOI18N

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelLateral.setBackground(new java.awt.Color(255, 255, 255));

        pagoButton.setBackground(new java.awt.Color(107, 219, 141));
        pagoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dollar-symbol (1).png"))); // NOI18N
        pagoButton.setText("Registrar Pagos");
        pagoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pagoButton.setBorderPainted(false);
        pagoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(231, 231, 231));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/searchLupa.png"))); // NOI18N
        jButton2.setText("Consultar Pagos");

        tipoPagoButton.setBackground(new java.awt.Color(231, 231, 231));
        tipoPagoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tag.png"))); // NOI18N
        tipoPagoButton.setText("Tipos de Pagos");
        tipoPagoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPagoButtonActionPerformed(evt);
            }
        });

        estudianteButton.setBackground(new java.awt.Color(231, 231, 231));
        estudianteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiante.png"))); // NOI18N
        estudianteButton.setText("Estudiantes");
        estudianteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudianteButtonActionPerformed(evt);
            }
        });

        represanteButton.setBackground(new java.awt.Color(231, 231, 231));
        represanteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/representantes.png"))); // NOI18N
        represanteButton.setText("Representantes");
        represanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                represanteButtonActionPerformed(evt);
            }
        });

        empleadoButton.setBackground(new java.awt.Color(231, 231, 231));
        empleadoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        empleadoButton.setText("Empleados");
        empleadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoButtonActionPerformed(evt);
            }
        });

        administradorButton.setBackground(new java.awt.Color(231, 231, 231));
        administradorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin.png"))); // NOI18N
        administradorButton.setText("Administrador");
        administradorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administradorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pagoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoPagoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estudianteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(represanteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(empleadoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(administradorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(pagoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tipoPagoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(estudianteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(represanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(empleadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(administradorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCambiante.setBackground(new java.awt.Color(255, 255, 255));
        panelCambiante.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String panelActual="";
    private void pagoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {           
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelPago panelPago = new PanelPago(); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelPago, "Pago"); // Agregar con nombre único
        card.show(panelCambiante, "Pago");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_pagoButtonActionPerformed

    private void represanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_represanteButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelRepresentante panelRepresentante=new PanelRepresentante(); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelRepresentante, "Representante"); // Agregar con nombre único
        card.show(panelCambiante, "Representante");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_represanteButtonActionPerformed

    private void empleadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelEmpleado panelEmpleado=new PanelEmpleado(); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelEmpleado, "Empleado"); // Agregar con nombre único
        card.show(panelCambiante, "Empleado");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_empleadoButtonActionPerformed

    private void administradorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administradorButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelAdmin panelAdmin=new PanelAdmin(); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelAdmin, "Admin"); // Agregar con nombre único
        card.show(panelCambiante, "Admin");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_administradorButtonActionPerformed

    private void estudianteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudianteButtonActionPerformed
       CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelEstudiante panelEstudiante=new PanelEstudiante(); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelEstudiante, "Estudiante"); // Agregar con nombre único
        card.show(panelCambiante, "Estudiante");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_estudianteButtonActionPerformed

    private void tipoPagoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPagoButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelTipoPago panelTipoPago=new PanelTipoPago(); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelTipoPago, "TipoPago"); // Agregar con nombre único
        card.show(panelCambiante, "TipoPago");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_tipoPagoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administradorButton;
    private javax.swing.JButton empleadoButton;
    private javax.swing.JButton estudianteButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton pagoButton;
    private javax.swing.JPanel panelCambiante;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JButton represanteButton;
    private javax.swing.JButton tipoPagoButton;
    // End of variables declaration//GEN-END:variables
}
