/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expoferia.pagos.gestionpagos.gui;

import expoferia.pagos.gestionpagos.gui.modulos.CarritoPago;
import expoferia.pagos.gestionpagos.gui.modulos.ConsultarPago;
import java.awt.*;
import expoferia.pagos.gestionpagos.gui.modulos.RegistroPago;
import expoferia.pagos.gestionpagos.gui.modulos.TablaConsultarPago;
import expoferia.pagos.gestionpagos.gui.tabla.DetallePagoTableModel;

import javax.swing.*;

/**
 *
 * @author Suglin
 */
public class SistemaCajero extends javax.swing.JFrame {

    public static CardLayout card;
    public static CardLayout card2;

    public SistemaCajero() {
        initComponents();
        setLocationRelativeTo(null);

        CarritoPago carritoPago = SesionActual.getCarritoPago();
        DetallePagoTableModel tableModel = SesionActual.getTableModel();
        carritoPago.setTablaModelo(tableModel);

        card = (CardLayout) panelRound1.getLayout();
        card2 = (CardLayout) panelRound2.getLayout();
        
        RegistroPago registroPago = new RegistroPago(carritoPago);
        panelRound1.add(registroPago, "regPago");
        card.show(panelRound1, "regPago");

        TablaConsultarPago consultarPago = new TablaConsultarPago(tableModel);
        panelRound2.add(consultarPago, "conPago");
        card2.show(panelRound2, "conPago");
        setTitle("Registrar Pagos - Cajero");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/IconGonzagaaaa.png")).getImage());

        // Estilo visual del botón salir
        botonToggleSalirCajero.setBorderPainted(false);
        botonToggleSalirCajero.setContentAreaFilled(false);
        botonToggleSalirCajero.setFocusPainted(true);
        botonToggleSalirCajero.setOpaque(false);

        //el cursor cambia a una mano 👆 cuando el usuario pase el mouse sobre el
        botonToggleSalirCajero.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        //Efecto visual: al pasar el mouse sobre el botón, se sombrea con fondo
        botonToggleSalirCajero.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonToggleSalirCajero.setBackground(new Color(220, 220, 220)); // color gris claro
                botonToggleSalirCajero.setOpaque(true); // para que el fondo se dibuje
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonToggleSalirCajero.setBackground(null); // vuelve a fondo transparente
                botonToggleSalirCajero.setOpaque(false);
            }
        });

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonToggleSalirCajero = new javax.swing.JToggleButton();
        panelCambiante = new expoferia.pagos.gestionpagos.gui.PanelRound();
        panelRound3 = new expoferia.pagos.gestionpagos.gui.PanelRound();
        panelRound1 = new expoferia.pagos.gestionpagos.gui.PanelRound();
        panelRound2 = new expoferia.pagos.gestionpagos.gui.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(220, 217, 217));

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 72, 162));
        jLabel3.setText("SISTEMA DE PAGOS COLEGIO GONZAGA");

        botonToggleSalirCajero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        botonToggleSalirCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonToggleSalirCajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonToggleSalirCajero)
                .addGap(23, 23, 23))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonToggleSalirCajero)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22))
        );

        panelCambiante.setBackground(new java.awt.Color(255, 255, 255));
        panelCambiante.setRoundBottomLeft(30);
        panelCambiante.setRoundBottomRight(30);
        panelCambiante.setRoundTopLeft(30);
        panelCambiante.setRoundTopRight(30);
        panelCambiante.setLayout(new java.awt.CardLayout());

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);

        panelRound1.setBackground(new java.awt.Color(102, 0, 204));
        panelRound1.setMinimumSize(new java.awt.Dimension(491, 410));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setLayout(new java.awt.CardLayout());

        panelRound2.setBackground(new java.awt.Color(0, 204, 204));
        panelRound2.setPreferredSize(new java.awt.Dimension(500, 410));
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopRight(30);
        panelRound2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound3Layout.createSequentialGroup()
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRound3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelCambiante.add(panelRound3, "card2");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonToggleSalirCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonToggleSalirCajeroActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Deseas salir del sistema?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0); // Cierra el sistema
        } else {
            botonToggleSalirCajero.setSelected(false); // Si cancela, desactiva el toggle
        }

    }//GEN-LAST:event_botonToggleSalirCajeroActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new SistemaCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonToggleSalirCajero;
    private javax.swing.JLabel jLabel3;
    private expoferia.pagos.gestionpagos.gui.PanelRound panelCambiante;
    private javax.swing.JPanel panelPrincipal;
    private expoferia.pagos.gestionpagos.gui.PanelRound panelRound1;
    private expoferia.pagos.gestionpagos.gui.PanelRound panelRound2;
    private expoferia.pagos.gestionpagos.gui.PanelRound panelRound3;
    private javax.swing.JPanel panelSuperior;
    // End of variables declaration//GEN-END:variables
}
