/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expoferia.pagos.gestionpagos.gui;

import java.awt.*;
import expoferia.pagos.gestionpagos.gui.modulos.PanelAdmin;
import expoferia.pagos.gestionpagos.gui.modulos.PanelDefault;
import expoferia.pagos.gestionpagos.gui.modulos.RegistroPago;

import javax.swing.JOptionPane;


/**
 *
 * @author Suglin
 */
public class SistemaAdmin extends javax.swing.JFrame {

    public static CardLayout card;

    public SistemaAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        card= (CardLayout) panelCambiante.getLayout();
        setTitle("Gestiones - Administrador");

        // Estilo visual del botón salir
        botonToggleSalir.setBorderPainted(false);
        botonToggleSalir.setContentAreaFilled(false);
        botonToggleSalir.setFocusPainted(true);
        botonToggleSalir.setOpaque(false);

        //el cursor cambia a una mano 👆 cuando el usuario pase el mouse sobre el
        botonToggleSalir.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        //Efecto visual: al pasar el mouse sobre el botón, se sombrea con fondo
        botonToggleSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonToggleSalir.setBackground(new Color(220, 220, 220)); // color gris claro
                botonToggleSalir.setOpaque(true); // para que el fondo se dibuje
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonToggleSalir.setBackground(null); // vuelve a fondo transparente
                botonToggleSalir.setOpaque(false);
            }
        });


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonToggleSalir = new javax.swing.JToggleButton();
        panelLateral = new expoferia.pagos.gestionpagos.gui.PanelRound();
        pagoButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tipoPagoButton = new javax.swing.JButton();
        estudianteButton = new javax.swing.JButton();
        represanteButton = new javax.swing.JButton();
        empleadoButton = new javax.swing.JButton();
        administradorButton = new javax.swing.JButton();
        panelCambiante = new expoferia.pagos.gestionpagos.gui.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(220, 217, 217));

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 72, 162));
        jLabel3.setText("SISTEMA DE PAGOS COLEGIO GONZAGA");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bars.png"))); // NOI18N

        botonToggleSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesion.png"))); // NOI18N
        botonToggleSalir.setBorderPainted(false);
        botonToggleSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonToggleSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonToggleSalir)
                .addGap(76, 76, 76))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(botonToggleSalir))
                        .addGap(5, 5, 5)))
                .addGap(13, 13, 13))
        );

        panelLateral.setBackground(new java.awt.Color(255, 255, 255));
        panelLateral.setRoundBottomRight(30);
        panelLateral.setRoundTopRight(30);

        pagoButton.setBackground(new java.awt.Color(107, 219, 141));
        pagoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dollar-symbol (1).png"))); // NOI18N
        pagoButton.setText("Registrar Pagos");
        pagoButton.setBorderPainted(false);
        pagoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(231, 231, 231));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/searchLupa.png"))); // NOI18N
        jButton2.setText("Consultar Pagos");

        tipoPagoButton.setBackground(new java.awt.Color(231, 231, 231));
        tipoPagoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tag.png"))); // NOI18N
        tipoPagoButton.setText("Tipos de Pagos");
        tipoPagoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPagoButtonActionPerformed(evt);
            }
        });

        estudianteButton.setBackground(new java.awt.Color(231, 231, 231));
        estudianteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiante.png"))); // NOI18N
        estudianteButton.setText("Estudiantes");
        estudianteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudianteButtonActionPerformed(evt);
            }
        });

        represanteButton.setBackground(new java.awt.Color(231, 231, 231));
        represanteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/representantes.png"))); // NOI18N
        represanteButton.setText("Representantes");
        represanteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                represanteButtonActionPerformed(evt);
            }
        });

        empleadoButton.setBackground(new java.awt.Color(231, 231, 231));
        empleadoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N
        empleadoButton.setText("Empleados");
        empleadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoButtonActionPerformed(evt);
            }
        });

        administradorButton.setBackground(new java.awt.Color(231, 231, 231));
        administradorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin.png"))); // NOI18N
        administradorButton.setText("Administrador");
        administradorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administradorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(administradorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pagoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estudianteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(represanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(empleadoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tipoPagoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pagoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoPagoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empleadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(represanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estudianteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(administradorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelCambiante.setBackground(new java.awt.Color(255, 255, 255));
        panelCambiante.setRoundBottomLeft(30);
        panelCambiante.setRoundBottomRight(30);
        panelCambiante.setRoundTopLeft(30);
        panelCambiante.setRoundTopRight(30);
        panelCambiante.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCambiante, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCambiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoButtonActionPerformed
//        CardLayout card = (CardLayout) panelCambiante.getLayout();
//
//        // Verificar si el panel ya existe antes de crearlo
//        if (panelCambiante.getComponentCount() > 0) {
//            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
//            System.gc();
//        }
//
//        RegistroPago registroPago=new RegistroPago(); // Crear el panel solo cuando sea necesario
//        panelCambiante.add(registroPago, "RegistroPago"); // Agregar con nombre único
//        card.show(panelCambiante, "RegistroPago");
//
//        // Refrescar la interfaz para evitar glitches
//        panelCambiante.revalidate();
//        panelCambiante.repaint();
    }//GEN-LAST:event_pagoButtonActionPerformed

    private void tipoPagoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPagoButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelDefault panelTipoPago= new PanelDefault("ID Categoría Costo Estado Acciones",
            "Tipos de Pagos"); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelTipoPago, "Tipos de Pagos"); // Agregar con nombre único
        card.show(panelCambiante, "Tipos de Pagos");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_tipoPagoButtonActionPerformed

    private void estudianteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudianteButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelDefault panelEstudiante= new PanelDefault("ID Cedula Nombres Apellidos, Estado",
                "Estudiantes"); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelEstudiante, "Estudiantes"); // Agregar con nombre único
        card.show(panelCambiante, "Estudiantes");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_estudianteButtonActionPerformed

    private void represanteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_represanteButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelDefault panelRepresentante= new PanelDefault("ID Cedula Nombres Apellidos Estado",
                "Representantes"); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelRepresentante, "Representantes"); // Agregar con nombre único

        card.show(panelCambiante, "Representantes");
        panelCambiante.revalidate();// Refrescar la interfaz para evitar glitches
        panelCambiante.repaint();
    }//GEN-LAST:event_represanteButtonActionPerformed

    private void empleadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelDefault panelEmpleado= new PanelDefault("ID Cedula Nombres Apellidos Rol, Estado",
            "Empleados"); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelEmpleado, "Empleados"); // Agregar con nombre único
        card.show(panelCambiante, "Empleados");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_empleadoButtonActionPerformed

    private void administradorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administradorButtonActionPerformed
        CardLayout card = (CardLayout) panelCambiante.getLayout();

        // Verificar si el panel ya existe antes de crearlo
        if (panelCambiante.getComponentCount() > 0) {
            panelCambiante.remove(0); // Elimina solo el primer panel en lugar de todos
            System.gc();
        }

        PanelAdmin panelAdmin=new PanelAdmin(); // Crear el panel solo cuando sea necesario
        panelCambiante.add(panelAdmin, "Admin"); // Agregar con nombre único
        card.show(panelCambiante, "Admin");

        // Refrescar la interfaz para evitar glitches
        panelCambiante.revalidate();
        panelCambiante.repaint();
    }//GEN-LAST:event_administradorButtonActionPerformed

    private void botonToggleSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonToggleSalirActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Deseas salir del sistema?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0); // Sale del sistema
        } else {
            botonToggleSalir.setSelected(false); // Si cancela, desactiva el botón
        }

    }//GEN-LAST:event_botonToggleSalirActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new SistemaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administradorButton;
    private javax.swing.JToggleButton botonToggleSalir;
    private javax.swing.JButton empleadoButton;
    private javax.swing.JButton estudianteButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton pagoButton;
    public static expoferia.pagos.gestionpagos.gui.PanelRound panelCambiante;
    private expoferia.pagos.gestionpagos.gui.PanelRound panelLateral;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JButton represanteButton;
    private javax.swing.JButton tipoPagoButton;
    // End of variables declaration//GEN-END:variables
}
