/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package expoferia.pagos.gestionpagos.gui.modulos;

import expoferia.pagos.gestionpagos.dao.EstudianteDAO;
import expoferia.pagos.gestionpagos.dao.PagoReciboDAO;
import expoferia.pagos.gestionpagos.dao.RepresentanteDAO;
import expoferia.pagos.gestionpagos.entidades.DetallesPago;
import expoferia.pagos.gestionpagos.entidades.Estudiante;
import expoferia.pagos.gestionpagos.entidades.PagoRecibo;
import com.toedter.calendar.JDateChooser;
import expoferia.pagos.gestionpagos.entidades.Representante;
import expoferia.pagos.gestionpagos.gui.tabla.DashboardPagoTableModel;
import expoferia.pagos.gestionpagos.gui.tabla.DefaultTable;

import javax.swing.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

/**
 *
 * @author USER
 */
public class Dashboard extends javax.swing.JPanel {

    JDateChooser dateChooser;
    List<PagoRecibo> listaPagos;
    DashboardPagoTableModel modelo = new DashboardPagoTableModel();
    Integer idPago;
    PagoRecibo pagoSelect;
    Estudiante estu;
    Representante repre;
    /**
     * Creates new form RegistroEmpleados
     */
    public Dashboard() {
        initComponents();

        dateChooser = new JDateChooser();

        SimpleDateFormat spf=new SimpleDateFormat("yyyy/MM/dd");
        // Configura el formato visible en el JDateChooser
        dateChooser.setDateFormatString("yyyy/MM/dd");

        // Convierte LocalDate a java.util.Date correctamente
        LocalDate hoy = LocalDate.now();
        Date fechaHoy = Date.valueOf(hoy);

        // Establece la fecha actual en el selector
        dateChooser.setDate(fechaHoy);

        dateChooser.setVisible(true);

        panelCalendario.add(dateChooser);
        jTable2.setModel(modelo);
        jTable2.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int filaSeleccionada = jTable2.rowAtPoint(e.getPoint());

                if (filaSeleccionada >= 0) {
                    // 🎯 Obtener ID desde la primera columna
                    Object valorId = jTable2.getValueAt(filaSeleccionada, 0);
                    idPago = Integer.parseInt(valorId.toString());

                    System.out.println("ID capturado: " + idPago);

                    Optional<PagoRecibo> pagoCoincidente = listaPagos.stream()
                            .filter(p -> p.getIdPagoRecibo() == idPago)
                            .findFirst();

                    if (pagoCoincidente.isPresent()) {
                        pagoSelect = pagoCoincidente.get();
                        llenarDatos();

                        // 🖱️ Detectar doble clic con botón izquierdo
                        if (e.getClickCount() == 2 && SwingUtilities.isLeftMouseButton(e)) {
                            mostrarDetallesPago(); // Aquí llamas tu método personalizado
                        }

                    } else {
                        vaciarDatos();
                    }

                } else {
                    vaciarDatos();
                }
            }
        });




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtregistrodeEmpleadoRE = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panelCalendario = new javax.swing.JPanel();
        panelDatosPago = new javax.swing.JPanel();
        datosRepre = new javax.swing.JLabel();
        datosEstu = new javax.swing.JLabel();
        datosCedula = new javax.swing.JLabel();
        datosGrado = new javax.swing.JLabel();
        datosNivel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtregistrodeEmpleadoRE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtregistrodeEmpleadoRE.setForeground(new java.awt.Color(10, 72, 162));
        txtregistrodeEmpleadoRE.setText("DASHBOARD");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(2, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Monto Total", "Monto Pagado", "Fecha", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/searchLupa.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        panelCalendario.setBackground(new java.awt.Color(255, 255, 255));
        panelCalendario.setLayout(new java.awt.BorderLayout());

        panelDatosPago.setBackground(new java.awt.Color(153, 153, 153));

        datosRepre.setForeground(new java.awt.Color(0, 0, 0));
        datosRepre.setText("Representante:");

        datosEstu.setForeground(new java.awt.Color(0, 0, 0));
        datosEstu.setText("Estudiante: ");

        datosCedula.setForeground(new java.awt.Color(0, 0, 0));
        datosCedula.setText("Cedula:");

        datosGrado.setForeground(new java.awt.Color(0, 0, 0));
        datosGrado.setText("Grado:");

        datosNivel.setForeground(new java.awt.Color(0, 0, 0));
        datosNivel.setText("Nivel Académico");

        jLabel2.setText("                  ");

        jLabel3.setText("                  ");

        jLabel4.setText("                  ");

        jLabel5.setText("                  ");

        jLabel6.setText("                  ");

        javax.swing.GroupLayout panelDatosPagoLayout = new javax.swing.GroupLayout(panelDatosPago);
        panelDatosPago.setLayout(panelDatosPagoLayout);
        panelDatosPagoLayout.setHorizontalGroup(
            panelDatosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosPagoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelDatosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosPagoLayout.createSequentialGroup()
                        .addComponent(datosGrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPagoLayout.createSequentialGroup()
                        .addComponent(datosNivel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosPagoLayout.createSequentialGroup()
                        .addComponent(datosCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(panelDatosPagoLayout.createSequentialGroup()
                        .addComponent(datosEstu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(panelDatosPagoLayout.createSequentialGroup()
                        .addComponent(datosRepre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(49, 49, 49))
        );
        panelDatosPagoLayout.setVerticalGroup(
            panelDatosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosPagoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelDatosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datosEstu)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(panelDatosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datosRepre)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(panelDatosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datosCedula)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(panelDatosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datosNivel)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(panelDatosPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datosGrado)
                    .addComponent(jLabel6))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtregistrodeEmpleadoRE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelDatosPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(panelCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtregistrodeEmpleadoRE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCalendario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDatosPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        listarPagos();
    }//GEN-LAST:event_jLabel1MouseClicked

    public void llenarDatos() {

        EstudianteDAO est = new EstudianteDAO();
        estu = est.buscarPorId(pagoSelect.getIdEstudiante());
        RepresentanteDAO rep = new RepresentanteDAO();
        repre = rep.buscarPorCedula(estu.getCedulaRep());

        jLabel2.setText(estu.getNombre1() + " " + estu.getApellido1());
        jLabel3.setText(repre.getNombre1() + " " + repre.getApellido1());
        jLabel4.setText(repre.getCedula());
        jLabel5.setText(estu.getNivel_academico());
        jLabel6.setText(estu.getGrado());

    }

    public void vaciarDatos() {

        jLabel2.setText("                  ");
        jLabel3.setText("                  ");
        jLabel4.setText("                  ");
        jLabel5.setText("                  ");
        jLabel6.setText("                  ");

    }

    public void listarPagos() {

        PagoReciboDAO pagoReciboDAO = new PagoReciboDAO();
        java.util.Date dateUtil = dateChooser.getDate();

        if (dateUtil != null) {
            listaPagos = pagoReciboDAO.listarPorFecha(new java.sql.Date (dateUtil.getTime()));

            if (!listaPagos.isEmpty()) {

                for (PagoRecibo pr : listaPagos) {

                    modelo.agregarFila(pr.getIdPagoRecibo(),
                            pr.getMontoTotal(),
                            pr.getMontoPagado(),
                            pr.getFechaPago(),
                            pr.getEstado()
                    );

                }
                dateChooser.cleanup();

        } else {
                JOptionPane.showMessageDialog(null, "No existen pagos realizados en esa fecha.");
            }


        } else {
            JOptionPane.showMessageDialog(null, "Debe escoger una fecha antes de buscar.");
            listaPagos = null;
        }

    }

    public void mostrarDetallesPago() {

        PagoReciboDAO pagoReciboDAO = new PagoReciboDAO();
        List<DetallesPago> detallesPagos = pagoReciboDAO.listarDetallesYAbonosPorRecibo(pagoSelect.getIdPagoRecibo());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datosCedula;
    private javax.swing.JLabel datosEstu;
    private javax.swing.JLabel datosGrado;
    private javax.swing.JLabel datosNivel;
    private javax.swing.JLabel datosRepre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panelCalendario;
    private javax.swing.JPanel panelDatosPago;
    private javax.swing.JLabel txtregistrodeEmpleadoRE;
    // End of variables declaration//GEN-END:variables
}
