/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package expoferia.pagos.gestionpagos.gui.modulos;

import expoferia.pagos.gestionpagos.dao.*;
import expoferia.pagos.gestionpagos.entidades.*;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.Date;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

/**
 *
 * @author Suglin
 */
public class RegistroPago extends javax.swing.JPanel {

    ArrayList<Estudiante> listE;
    Representante representante;
    Estudiante estudiante;
    TipoPago tipoPago;
    CarritoPago carritoPago;
    String metodoPago;
    boolean aplicaMora=false;
    DetallesPago mesAPagar;
    private static final List<String> MESES_ESCOLARES = Arrays.asList(
            "Septiembre", "Octubre", "Noviembre", "Diciembre",
            "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto"
    );
    AnioEscolar anioEscolar;
    String mesPendiente;

    /**
     * Creates new form Registro
     */
    public RegistroPago(CarritoPago carritoPago) {
        initComponents();
        this.carritoPago = carritoPago;
        AnoEscolarDAO aEDao = new AnoEscolarDAO();
        anioEscolar = aEDao.obtenerPeriodoActivo();
        PagoReciboDAO pRDao = new PagoReciboDAO();
        datosNFactura.setText(String.valueOf(pRDao.obtenerProximoIdPagoRecibo()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        metodoPagos = new javax.swing.ButtonGroup();
        abonoPago = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        comboEstudiantes = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        datosRepre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        datosEstu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        gradoEstu = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        datosFecha = new javax.swing.JLabel();
        datosNFactura = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        datosTasa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        comboTPago = new javax.swing.JComboBox<>();
        checkAbono = new java.awt.Checkbox();
        jLabel18 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        radioTransferencia = new javax.swing.JRadioButton();
        radioDebito = new javax.swing.JRadioButton();
        radioEfectivo = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        txtTReferencia = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        comboEstudiantes.setBackground(new java.awt.Color(255, 255, 255));
        comboEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        comboEstudiantes.setForeground(new java.awt.Color(0, 0, 0));
        comboEstudiantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un Estudiante" }));
        comboEstudiantes.setToolTipText("");
        comboEstudiantes.setAutoscrolls(true);
        comboEstudiantes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        comboEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboEstudiantes.setDoubleBuffered(true);
        comboEstudiantes.setPreferredSize(new java.awt.Dimension(195, 18));
        comboEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstudiantesActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(244, 244, 244));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setEnabled(false);
        jSeparator1.setFocusTraversalPolicyProvider(true);
        jSeparator1.setFocusable(true);
        jSeparator1.setInheritsPopupMenu(true);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");
        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Datos del Representate:");

        datosRepre.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        datosRepre.setForeground(new java.awt.Color(0, 0, 0));
        datosRepre.setText("               ");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Datos del Estudiante:");

        datosEstu.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        datosEstu.setForeground(new java.awt.Color(0, 0, 0));
        datosEstu.setText("               ");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Datos Grado/Año:");

        gradoEstu.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        gradoEstu.setForeground(new java.awt.Color(0, 0, 0));
        gradoEstu.setText("            ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(datosRepre)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datosEstu)
                    .addComponent(jLabel8)
                    .addComponent(gradoEstu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosRepre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datosEstu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradoEstu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Fecha:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("N# Factura:");

        datosFecha.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        datosFecha.setForeground(new java.awt.Color(0, 0, 0));
        datosFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datosFecha.setText("                       ");

        datosNFactura.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        datosNFactura.setForeground(new java.awt.Color(0, 0, 0));
        datosNFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datosNFactura.setText("                       ");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Tasa BCV");

        datosTasa.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        datosTasa.setForeground(new java.awt.Color(0, 0, 0));
        datosTasa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        datosTasa.setText("                     ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datosFecha))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datosNFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datosTasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(datosFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(datosNFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(datosTasa))
                .addContainerGap())
        );

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 72, 162));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro De Pagos");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btnLimpiar.setBackground(new java.awt.Color(204, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cédula de Representante");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Estudiantes del representante");

        btnImprimir.setBackground(new java.awt.Color(3, 105, 173));
        btnImprimir.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("Imprimir");
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));

        jLabel16.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Concepto de Pago");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtConcepto.setEditable(false);
        txtConcepto.setBackground(new java.awt.Color(255, 255, 255));
        txtConcepto.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtConcepto.setForeground(new java.awt.Color(0, 0, 0));
        txtConcepto.setToolTipText("");
        txtConcepto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConceptoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Monto");

        txtMonto.setBackground(new java.awt.Color(255, 255, 255));
        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        txtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMonto.setActionCommand("<Not Set>");
        txtMonto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtMonto.setEnabled(false);
        txtMonto.setPreferredSize(new java.awt.Dimension(64, 13));
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tipo de Pago");

        comboTPago.setBackground(new java.awt.Color(255, 255, 255));
        comboTPago.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        comboTPago.setForeground(new java.awt.Color(0, 0, 0));
        comboTPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un tipo", "Mensualidad", "Inscripción", "Curso", "Cuota Extra" }));
        comboTPago.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        comboTPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboTPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTPagoActionPerformed(evt);
            }
        });

        checkAbono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkAbono.setEnabled(false);
        checkAbono.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        checkAbono.setLabel("Abono");
        checkAbono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkAbonoMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Metodo de Pago");

        btnGuardar.setBackground(new java.awt.Color(3, 105, 173));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Agregar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        metodoPagos.add(radioTransferencia);
        radioTransferencia.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        radioTransferencia.setForeground(new java.awt.Color(0, 0, 0));
        radioTransferencia.setText("Transferencia");
        radioTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radioTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTransferenciaActionPerformed(evt);
            }
        });

        metodoPagos.add(radioDebito);
        radioDebito.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        radioDebito.setForeground(new java.awt.Color(0, 0, 0));
        radioDebito.setText("Debito");
        radioDebito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radioDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDebitoActionPerformed(evt);
            }
        });

        metodoPagos.add(radioEfectivo);
        radioEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        radioEfectivo.setForeground(new java.awt.Color(0, 0, 0));
        radioEfectivo.setText("Efectivo");
        radioEfectivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radioEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEfectivoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("N# Referencia");

        txtTReferencia.setBackground(new java.awt.Color(255, 255, 255));
        txtTReferencia.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtTReferencia.setForeground(new java.awt.Color(0, 0, 0));
        txtTReferencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTReferencia.setActionCommand("<Not Set>");
        txtTReferencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtTReferencia.setEnabled(false);
        txtTReferencia.setMinimumSize(new java.awt.Dimension(64, 18));
        txtTReferencia.setPreferredSize(new java.awt.Dimension(64, 13));
        txtTReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTReferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(comboTPago, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(radioDebito)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioTransferencia))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(btnGuardar)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioEfectivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboTPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radioDebito)
                                    .addComponent(radioTransferencia)
                                    .addComponent(radioEfectivo)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(checkAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        txtcedula.setBackground(new java.awt.Color(255, 255, 255));
        txtcedula.setFont(new java.awt.Font("Segoe UI", 0, 9)); // NOI18N
        txtcedula.setForeground(new java.awt.Color(0, 0, 0));
        txtcedula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/searchLupa.png"))); // NOI18N
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(3, 105, 173));
        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimir)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscar))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(comboEstudiantes, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(btnConsultar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnImprimir))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstudiantesActionPerformed
        seleccionarE();
    }//GEN-LAST:event_comboEstudiantesActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        registrarPago();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConceptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConceptoActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed

    }//GEN-LAST:event_txtMontoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        anadirConcepto();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtTReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTReferenciaActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        buscarR();
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        if (estudiante != null) {
            busquedaMeses();
        } else JOptionPane.showMessageDialog(null, "Debe de seleccionar un estudiante para poder consultar sus pagos.");

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void comboTPagoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_comboTPagoActionPerformed

        if (estudiante != null) {
            checkAbono.setState(false);

            if (!comboTPago.getSelectedItem().equals("Seleccione un tipo")) {

                TipoPagoDAO tDao = new TipoPagoDAO();
                tipoPago = tDao.buscarPorCategoria(comboTPago.getSelectedItem().toString());

                txtMonto.setText(String.valueOf(tipoPago.getCosto()));

                if (tipoPago.getCategoria().equals("Curso") || tipoPago.getCategoria().equals("Cuota Extra") || tipoPago.getCategoria().equals("Inscripción")) {
                    txtConcepto.setText("Pago "+tipoPago.getCategoria());
                } else txtMonto.setEnabled(false);

                if (tipoPago.getCategoria().equals("Mensualidad")) {

                    checkAbono.setEnabled(true);
                    mesAPagar = buscarPrimerMesPendiente();
                    mesPendiente = mesAPagar.getMesCorrespondiente();

                    if (mesAPagar.tieneSaldoPendiente()) {

                        txtConcepto.setText("Abono " + mesPendiente);
                        txtMonto.setText(String.valueOf(mesAPagar.getDiferencia()));
                        System.out.println("Tiene un abono pendiente del mes "+mesPendiente+" de: "+mesAPagar.getDiferencia());
                    }
                    else if (tieneMoraParaMes(mesPendiente)) {

                        txtConcepto.setText("Mora "+mesPendiente);

                        txtMonto.setText(String.valueOf(tipoPago.getCosto()+5));
                        aplicaMora = true;
                        System.out.println("Tiene mora para el mes de: "+mesPendiente);
                        tipoPago.setCosto(Double.parseDouble(txtMonto.getText()));

                    } else {
                        System.out.println("No tiene mora para el mes de: "+mesPendiente);
                        txtConcepto.setText("Pago "+mesPendiente);

                    }

                }
                else checkAbono.setEnabled(false);
            } else checkAbono.setEnabled(false);
        }  else {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un estudiante antes de manejar los tipos de pago.");
            comboTPago.setSelectedIndex(0);
        }

    }//GEN-LAST:event_comboTPagoActionPerformed

    private void radioEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEfectivoActionPerformed

        txtTReferencia.setText("");
        txtTReferencia.setEnabled(false);
        metodoPago="Efectivo";

    }//GEN-LAST:event_radioEfectivoActionPerformed

    private void radioTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTransferenciaActionPerformed

        txtTReferencia.setEnabled(true);
        metodoPago="Transferencia";


    }//GEN-LAST:event_radioTransferenciaActionPerformed

    private void radioDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDebitoActionPerformed

        txtTReferencia.setEnabled(true);
        metodoPago="Débito";

    }//GEN-LAST:event_radioDebitoActionPerformed

    private void checkAbonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAbonoMouseClicked

        if (!checkAbono.getState()) {

            txtMonto.setEnabled(true);
            txtConcepto.setText(((aplicaMora) ? "Abono de mora "+ mesPendiente : "Pago "+ mesPendiente));

        } else {
            txtMonto.setEnabled(false);
            txtConcepto.setText(((aplicaMora) ? "Mora "+ mesPendiente : "Pago "+ mesPendiente));

        }

    }//GEN-LAST:event_checkAbonoMouseClicked

    private boolean validarCampos() {

        if (representante == null) {
            JOptionPane.showMessageDialog(null, "Debe de ingresar la cédula de un representante existente.");
            return false;
        }
        if (estudiante == null) {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un estudiante antes de registrar un concepto.");
            return false;
        }
        if (comboTPago.getSelectedItem().toString().matches("Seleccione un tipo")) {
            JOptionPane.showMessageDialog(null, "Debe de elegir un tipo de pago.");
            return false;
        }
        if (txtMonto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El monto no puede quedar vacío.");
            return false;
        }
        if (!txtMonto.getText().matches("^\\d+(\\.\\d+)?$")) {
            JOptionPane.showMessageDialog(null, "El monto solo debe contener números positivos y decimales.");
            return false;
        }
        if (Double.parseDouble(txtMonto.getText())<=0) {
            JOptionPane.showMessageDialog(null, "El monto no puede ser menor o igual a 0.");
            return false;
        }
        if (txtConcepto.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "El concepto no puede quedar vacío.");
            return false;
        }
        if (!txtConcepto.getText().matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$")) {
            JOptionPane.showMessageDialog(null, "El concepto solo puede contener palabras.");
            return false;
        }
        if (metodoPagos.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un método de pago.");
            return false;
        }
        if (txtTReferencia.isEnabled()) {
            if (txtTReferencia.getText().isBlank()) {
                JOptionPane.showMessageDialog(null, "El número de referencia no puede quedar vacío.");
                return false;
            }
        }
        if (txtTReferencia.isEnabled()) {
            if (!txtTReferencia.getText().matches("^\\d+$")) {
                JOptionPane.showMessageDialog(null, "El número de referencia solo puede contener números.");
                return false;
            }
        }

        return true;
    }

    private void buscarR() {

        if (!txtcedula.getText().isBlank()) {

            if (txtcedula.getText().matches("V"+"\\d+")) {

                RepresentanteDAO rDao = new RepresentanteDAO();
                representante = rDao.buscarPorCedula(txtcedula.getText());
                if (representante != null) {

                    System.out.println("Representante encontrado: "+representante.getNombre1());
                    JOptionPane.showMessageDialog(null, "Representante encontrado!");
                    datosRepre.setText(representante.getNombre1()+" "+representante.getApellido1());

                    EstudianteDAO eDao = new EstudianteDAO();
                    listE = eDao.obtenerEVinculados(txtcedula.getText());

                    String index0 = comboEstudiantes.getItemAt(0);
                    comboEstudiantes.removeAllItems();
                    comboEstudiantes.addItem(index0);

                    for (Estudiante e : listE) {

                        comboEstudiantes.addItem(e.getNombre1()+" "+e.getApellido2());

                    }

                } else JOptionPane.showMessageDialog(null, "No existe un representante con esta cédula.");

            } else JOptionPane.showMessageDialog(null, "La cédula debe contener V y solo números.");


        } else JOptionPane.showMessageDialog(null, "La cédula no puede quedar vacía.");

    }

    private void seleccionarE() {

        int index = comboEstudiantes.getSelectedIndex();

        if (index > 0) {

            estudiante = listE.get(index-1);
            datosEstu.setText(estudiante.getNombre1()+" "+estudiante.getApellido1());
            gradoEstu.setText(estudiante.getGrado());

        } else {
            datosEstu.setText("               ");
            estudiante = null;
        }
    }

    private void resetCamposPago() {

        txtMonto.setText("");
        comboTPago.setSelectedIndex(0);
        txtConcepto.setText("");
        txtTReferencia.setText("");
        metodoPagos.clearSelection();
        checkAbono.setState(false);

    }

    private void anadirConcepto() {

        if (validarCampos()) {

            if (mesAPagar.tieneSaldoPendiente()) {

                Abono abono = new Abono();
                abono.setIdDetallesPago(mesAPagar.getId());
                abono.setFechaAbono(LocalDate.now());
                abono.setMetodoPago(metodoPago);
                if (txtTReferencia.isEnabled()) abono.setNumTrans(txtTReferencia.getText());
                else abono.setNumTrans(null);
                abono.setMontoAbonado(Double.parseDouble(txtMonto.getText()));
                abono.setDescripcion(txtConcepto.getText());
                carritoPago.agregarAbono(abono);
                resetCamposPago();
                JOptionPane.showMessageDialog(null, "Abono agregado al pago!");                mesAPagar = null;
            }
            else {

                DetallesPago detallePago = new DetallesPago();

                detallePago.setIdTipoPago(tipoPago.getId());
                detallePago.setMetodoPago(metodoPago);
                if (txtTReferencia.isEnabled()) detallePago.setNumTrans(txtTReferencia.getText());
                else detallePago.setNumTrans(null);

                detallePago.setIdAnoEscolar(anioEscolar.getIdAnoEscolar());
                detallePago.setDescripcion(txtConcepto.getText());

                // Asignación automática del mes más lejano que tiene pendiente si es una mensualidad
                if (tipoPago.getCategoria().equals("Mensualidad")) {
                    detallePago.setMesCorrespondiente(mesPendiente);
                }
                detallePago.setMontoPagado(Double.parseDouble(txtMonto.getText()));

                // Asignación del monto total del tipo de pago
                detallePago.setMontoTotal(tipoPago.getCosto());
                carritoPago.agregarConcepto(detallePago);

                if (detallePago.tieneSaldoPendiente()) JOptionPane.showMessageDialog(null, "Abono agregado al pago!");
                else JOptionPane.showMessageDialog(null, "Concepto agregado al pago!");

                resetCamposPago();
            }

        }

    }

    private void registrarPago() {

        if (comboEstudiantes.getSelectedItem() != "Seleccione un estudiante" && estudiante != null) {

            // Si registrará detalles pago y abonos
            if (!carritoPago.estaVacio() && !carritoPago.estaVacioAbono()) {

                AbonoDAO abonoDAO = new AbonoDAO();
                boolean exito = registrarSoloDetalle();
                boolean exito2 = abonoDAO.agregarAbono(carritoPago.getAbonos());

                if (exito && exito2) {
                    JOptionPane.showMessageDialog(null, "Pago registrado con éxito.");
                    limpiarCampos();
                }
                else JOptionPane.showMessageDialog(null, "Ocurrió un error al registrar el pago.");

            } //Si registrará solo detalles pago
            else if (!carritoPago.estaVacio()) {

                boolean exito = registrarSoloDetalle();
                if (exito) {
                    JOptionPane.showMessageDialog(null, "Pago registrado con éxito.");
                    limpiarCampos();
                }
                else JOptionPane.showMessageDialog(null, "Ocurrió un error al registrar el pago.");

            }  // Si registrará solo abonos
            else if (!carritoPago.estaVacioAbono()) {

                AbonoDAO abonoDAO = new AbonoDAO();
                boolean exito = abonoDAO.agregarAbono(carritoPago.getAbonos());
                if (exito) {
                    JOptionPane.showMessageDialog(null, "Pago registrado con éxito.");
                    limpiarCampos();
                }
                else JOptionPane.showMessageDialog(null, "Ocurrió un error al registrar el pago.");

            } else JOptionPane.showMessageDialog(null, "Primero debe registrar conceptos al pago.");

        } else JOptionPane.showMessageDialog(null, "Debe seleccionar un estudiante antes de crear el pago.");

    }

    private boolean registrarSoloDetalle() {

        boolean exito = false;

        int opcion = JOptionPane.showConfirmDialog(null, "Confirmar", "¿Desea imprimir el recibo?", JOptionPane.YES_NO_OPTION);

        if (opcion == 0) {
            PagoRecibo pagoRecibo = new PagoRecibo();
            PagoReciboDAO pRDao = new PagoReciboDAO();

            pagoRecibo.setIdEstudiante(estudiante.getId());

            pagoRecibo.setMontoTotal(carritoPago.calcularTotal());

            pagoRecibo.setMontoPagado(carritoPago.calcularTotalPagado());

            // Esto considera "pagado" si la diferencia entre los montos es menor a 0.001 (un milésimo)
            final double TOLERANCIA = 0.001;
            boolean pagado = Math.abs(pagoRecibo.getMontoPagado() - pagoRecibo.getMontoTotal()) < TOLERANCIA;
            pagoRecibo.setEstado(pagado);

            Date fechaSql = new Date(System.currentTimeMillis());
            pagoRecibo.setFechaPago(fechaSql);

            exito = pRDao.registrarPago(pagoRecibo, carritoPago.getConceptos());
        }
        return exito;
    }

    private void limpiarCampos() {

        comboEstudiantes.setSelectedIndex(0);
        txtcedula.setText("");
        representante=null;
        estudiante=null;
        datosEstu.setText("               ");
        datosRepre.setText("               ");
        gradoEstu.setText("               ");

        resetCamposPago();
        comboEstudiantes.removeAll();
        comboEstudiantes.addItem("Seleccione un Estudiante");
        carritoPago.limpiar();
        carritoPago.limpiarAbonos();
    }

    private List<String> busquedaMeses() {

        if (anioEscolar != null ) {
            DetallesPagoDAO dPDao = new DetallesPagoDAO();
            List<String> mesesPagados = dPDao.obtenerMesesPagados(estudiante.getId(), 1);
            List<String> mesesPendientes = new ArrayList<>();

            for (String mes : MESES_ESCOLARES) {
                if (!mesesPagados.contains(mes)) {
                    mesesPendientes.add(mes);
                }

            }
            System.out.println("Pagados: " + (!mesesPagados.isEmpty() ? mesesPagados : "Debe la vida."));
            System.out.println("Pendientes: "+mesesPendientes);
            return mesesPendientes;
        } else JOptionPane.showMessageDialog(null, "No se encontró un año escolar activo.");
       return null;

    }

    private DetallesPago buscarPrimerMesPendiente() {
        if (anioEscolar == null) return null;

        DetallesPagoDAO dPDao = new DetallesPagoDAO();
        List<DetallesPago> pagados = dPDao.listarPorEstudiante(estudiante.getId(), anioEscolar.getIdAnoEscolar());

        List<Abono> abonosEnCarrito = carritoPago.getAbonos();

        if (!abonosEnCarrito.isEmpty()) {
            Map<Integer, Double> sumasAbonos = abonosEnCarrito.stream()
                    .collect(Collectors.groupingBy(
                            Abono::getIdDetallesPago,
                            Collectors.summingDouble(Abono::getMontoAbonado)
                    ));

            for (DetallesPago dp : pagados) {
                double extra = sumasAbonos.getOrDefault(dp.getId(), 0.0);
                if (extra > 0) {
                    dp.setMontoPagado(dp.getMontoPagado() + extra);
                }
            }
        }

        for (DetallesPago dp : pagados) {
            System.out.println(dp.getMesCorrespondiente());
        }

        // Primero se confirma que no haya un saldo pendiente en las mensualidades de antes, para tenerlo como prioridad a pagar
        for (DetallesPago deuda : pagados) {
            if (deuda.tieneSaldoPendiente()) {
                return deuda;
            }
        }

        // ➕ Agregar los meses ya cargados al carrito
        for (DetallesPago dp : carritoPago.getConceptos()) {
            if (dp.esMensualidad()) {
                pagados.add(dp);
            }
        }

        List<String> mesesCubiertos = pagados.stream()
                .filter(DetallesPago::esMensualidad)
                .filter(dp -> !dp.tieneSaldoPendiente()) // ❗ Solo mensualidades pagadas totalmente
                .map(DetallesPago::getMesCorrespondiente)
                .toList();

        // 📌 Encontrar el primer mes que no esté en la lista de pagados
        for (String mes : MESES_ESCOLARES) {
            if (!mesesCubiertos.contains(mes)) {
                // Aquí puedes crear un nuevo DetallesPago o retornar el mes pendiente
                DetallesPago pendiente = new DetallesPago();
                pendiente.setMesCorrespondiente(mes);
                return pendiente;
            }
        }


        return null; // Todos los meses fueron pagados
    }

    public List<String> obtenerMesesMorosos(int idEstudiante, int idAnoEscolar) {

        List<String> pendientes = busquedaMeses();
        LocalDate hoy = LocalDate.now();
        List<String> morosos = new ArrayList<>();

        List<String> mesesOrdenados = Arrays.asList(
                "Septiembre", "Octubre", "Noviembre", "Diciembre",
                "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio"
        );

        for (String mes : pendientes) {
            int indexMes = mesesOrdenados.indexOf(mes);
            if (indexMes == -1) continue;

            int numeroMes = (indexMes + 9 > 12) ? (indexMes - 3) : (indexMes + 9);
            int anio = (indexMes + 9 > 12) ? hoy.getYear() + 1 : hoy.getYear();

            LocalDate fechaLimite = LocalDate.of(anio, numeroMes, 5);

            if (hoy.isAfter(fechaLimite)) {
                morosos.add(mes); // Solo se agrega si ya venció
            }
        }

        return morosos;
    }

    public boolean tieneMoraParaMes(String mesEscolar) {
        if (mesEscolar == null || anioEscolar == null) return false;

        List<String> mesesEscolares = Arrays.asList(
                "Septiembre", "Octubre", "Noviembre", "Diciembre",
                "Enero", "Febrero", "Marzo", "Abril",
                "Mayo", "Junio", "Julio", "Agosto"
        );

        int index = mesesEscolares.indexOf(mesEscolar);
        if (index == -1) return false;

        int numeroMes = (index + 9) % 12;
        if (numeroMes == 0) numeroMes = 12;

        // Año base tomado del periodo escolar actual
        LocalDate inicioPeriodo = anioEscolar.getPeriodoInicio().toLocalDate();
        int anioBase = inicioPeriodo.getYear();

        int anioFinal = (numeroMes >= 9) ? anioBase : anioBase + 1;

        LocalDate fechaLimite = LocalDate.of(anioFinal, numeroMes, 5);

        return LocalDate.now().isAfter(fechaLimite);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup abonoPago;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private java.awt.Checkbox checkAbono;
    private javax.swing.JComboBox<String> comboEstudiantes;
    private javax.swing.JComboBox<String> comboTPago;
    private javax.swing.JLabel datosEstu;
    private javax.swing.JLabel datosFecha;
    private javax.swing.JLabel datosNFactura;
    private javax.swing.JLabel datosRepre;
    private javax.swing.JLabel datosTasa;
    private javax.swing.JLabel gradoEstu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.ButtonGroup metodoPagos;
    private javax.swing.JRadioButton radioDebito;
    private javax.swing.JRadioButton radioEfectivo;
    private javax.swing.JRadioButton radioTransferencia;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtTReferencia;
    private javax.swing.JTextField txtcedula;
    // End of variables declaration//GEN-END:variables
}
