/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package expoferia.pagos.gestionpagos.gui.panelcambiante;

/**
 *
 * @author Suglin
 */

import expoferia.pagos.gestionpagos.dao.RepresentanteDAO;
import expoferia.pagos.gestionpagos.gui.panelcambiante.componentes.DefaultTable;
import expoferia.pagos.gestionpagos.gui.panelcambiante.componentes.Tabla;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class PanelDefault extends JPanel {
    private Tabla tabla;
    private RepresentanteDAO rdao;
    /**
     * Creates new form PanelRepresentante
     */

    public PanelDefault(String titulo, String nombresColumnas, String nombreTabla) {

        initComponents();
        jLabel8.setText(titulo);
        List<String> listaColumnas = new ArrayList<>();
        listaColumnas.addAll(Arrays.asList(nombresColumnas.split(" ")));

        tabla=new Tabla(nombreTabla, listaColumnas);
        rdao=new RepresentanteDAO();
        panelTabla.setLayout(new BorderLayout());
        JScrollPane scrollPane=new JScrollPane(tabla);
        panelTabla.add(scrollPane, BorderLayout.CENTER);
        scrollPane.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY, 2));
        tabla.setDefaultRenderer(Object.class, new DefaultTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRepresentantes = new JPanel();
        jLabel8 = new JLabel();
        registrarButton = new JButton();
        actualizarButton = new JButton();
        archivarButton = new JButton();
        jComboBox1 = new JComboBox<>();
        jLabel1 = new JLabel();
        panelTabla = new JPanel();

        panelRepresentantes.setBackground(new Color(255, 255, 255));
        panelRepresentantes.setMaximumSize(new Dimension(787, 445));

        jLabel8.setFont(new Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new Color(10, 72, 162));
        jLabel8.setText("Gestión de Representantes");

        registrarButton.setBackground(new Color(3, 105, 173));
        registrarButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        registrarButton.setForeground(new Color(255, 255, 255));
        registrarButton.setText("Agregar");

        actualizarButton.setBackground(new Color(3, 105, 173));
        actualizarButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        actualizarButton.setForeground(new Color(255, 255, 255));
        actualizarButton.setText("Actualizar");
        actualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarButtonActionPerformed(evt);
            }
        });

        archivarButton.setBackground(new Color(255, 51, 51));
        archivarButton.setFont(new Font("Segoe UI", 1, 12)); // NOI18N
        archivarButton.setForeground(new Color(255, 255, 255));
        archivarButton.setText("Archivar");

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Buscar ", "ID Trabajador ", "Cedula ", "Nombre " }));

        jLabel1.setIcon(new ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N

        panelTabla.setBackground(new Color(255, 255, 255));

        GroupLayout panelTablaLayout = new GroupLayout(panelTabla);
        panelTabla.setLayout(panelTablaLayout);
        panelTablaLayout.setHorizontalGroup(
            panelTablaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );
        panelTablaLayout.setVerticalGroup(
            panelTablaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        GroupLayout panelRepresentantesLayout = new GroupLayout(panelRepresentantes);
        panelRepresentantes.setLayout(panelRepresentantesLayout);
        panelRepresentantesLayout.setHorizontalGroup(
            panelRepresentantesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(panelRepresentantesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelRepresentantesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelRepresentantesLayout.createSequentialGroup()
                        .addComponent(registrarButton)
                        .addGap(32, 32, 32)
                        .addComponent(actualizarButton)
                        .addGap(34, 34, 34)
                        .addComponent(archivarButton)
                        .addGap(43, 43, 43)
                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addComponent(jLabel8))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelTabla, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRepresentantesLayout.setVerticalGroup(
            panelRepresentantesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, panelRepresentantesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelRepresentantesLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(panelRepresentantesLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(registrarButton)
                        .addComponent(actualizarButton)
                        .addComponent(archivarButton)
                        .addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelTabla, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(panelRepresentantes, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(panelRepresentantes, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void actualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton actualizarButton;
    private JButton archivarButton;
    private JComboBox<String> jComboBox1;
    private JLabel jLabel1;
    private JLabel jLabel8;
    private JPanel panelRepresentantes;
    private JPanel panelTabla;
    private JButton registrarButton;
    // End of variables declaration//GEN-END:variables
}
