/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package expoferia.pagos.gestionpagos.gui.formularios;

/**
 *
 * @author USER
 */
public class ActualizarEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarEmpleado
     */
    public ActualizarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textfieldSegundoNombreAE = new javax.swing.JTextField();
        txtPrimerApellidoAE = new javax.swing.JLabel();
        txtSegundoApellidoAE = new javax.swing.JLabel();
        textfieldPrimerApellidoAE = new javax.swing.JTextField();
        textfieldSegundoApellidoAE = new javax.swing.JTextField();
        cargoaCumplirComboBoxAE = new javax.swing.JComboBox<>();
        txtCargoaCuplirAE = new javax.swing.JLabel();
        textfieldTelefonoAE = new javax.swing.JTextField();
        txtTelefonoAE = new javax.swing.JLabel();
        barraTituloAE = new javax.swing.JPanel();
        txtConfirmarClaveAE = new javax.swing.JLabel();
        botonVolverAE = new javax.swing.JLabel();
        textfieldConfirmarClaveAE = new javax.swing.JTextField();
        txtregistrodeEmpleadoAE = new javax.swing.JLabel();
        txtDireccionAE = new javax.swing.JLabel();
        botonBorrarAE = new javax.swing.JLabel();
        textfieldDireccionAE = new javax.swing.JTextField();
        txtClaveAE = new javax.swing.JLabel();
        botonGuardarAE = new javax.swing.JButton();
        textfieldClaveAE = new javax.swing.JTextField();
        textfieldPrimerNombreAE = new javax.swing.JTextField();
        txtPrimerNombreAE = new javax.swing.JLabel();
        txtCedulaAE = new javax.swing.JLabel();
        textfieldCedulaAE = new javax.swing.JTextField();
        txtCorreoAE = new javax.swing.JLabel();
        textfieldCorreoAE = new javax.swing.JTextField();
        txtSegundoNombreAE = new javax.swing.JLabel();

        textfieldSegundoNombreAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldSegundoNombreAEActionPerformed(evt);
            }
        });

        txtPrimerApellidoAE.setText("Primer Apellido");

        txtSegundoApellidoAE.setText("Segundo Apellido");

        textfieldSegundoApellidoAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldSegundoApellidoAEActionPerformed(evt);
            }
        });

        cargoaCumplirComboBoxAE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un cargo", "Administrador", "Cajero" }));

        txtCargoaCuplirAE.setText("Cargo a Cumplir");

        txtTelefonoAE.setText("Telefono");

        barraTituloAE.setBackground(new java.awt.Color(204, 204, 204));
        barraTituloAE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        barraTituloAE.setPreferredSize(new java.awt.Dimension(2, 10));

        javax.swing.GroupLayout barraTituloAELayout = new javax.swing.GroupLayout(barraTituloAE);
        barraTituloAE.setLayout(barraTituloAELayout);
        barraTituloAELayout.setHorizontalGroup(
            barraTituloAELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        barraTituloAELayout.setVerticalGroup(
            barraTituloAELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        txtConfirmarClaveAE.setText("Confirmar clave");

        botonVolverAE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/volver-flecha.png"))); // NOI18N

        txtregistrodeEmpleadoAE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtregistrodeEmpleadoAE.setForeground(new java.awt.Color(10, 72, 162));
        txtregistrodeEmpleadoAE.setText("ACTUALIZAR DE EMPLEADOS");

        txtDireccionAE.setText("Dirección");

        botonBorrarAE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N

        textfieldDireccionAE.setActionCommand("<Not Set>");
        textfieldDireccionAE.setEnabled(false);
        textfieldDireccionAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldDireccionAEActionPerformed(evt);
            }
        });

        txtClaveAE.setText("Clave");

        botonGuardarAE.setBackground(new java.awt.Color(3, 105, 173));
        botonGuardarAE.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarAE.setText("Guardar");

        txtPrimerNombreAE.setText("Primer nombre");

        txtCedulaAE.setText("Cedula");

        txtCorreoAE.setText("Correo");

        txtSegundoNombreAE.setText("Segundo Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barraTituloAE, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonVolverAE)
                                .addGap(18, 18, 18)
                                .addComponent(txtregistrodeEmpleadoAE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(botonGuardarAE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrimerNombreAE)
                            .addComponent(textfieldPrimerNombreAE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldSegundoNombreAE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSegundoNombreAE)
                            .addComponent(textfieldPrimerApellidoAE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrimerApellidoAE)
                            .addComponent(textfieldSegundoApellidoAE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSegundoApellidoAE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtDireccionAE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTelefonoAE)
                                        .addComponent(textfieldTelefonoAE)
                                        .addComponent(txtCorreoAE)
                                        .addComponent(txtCedulaAE)
                                        .addComponent(textfieldCedulaAE)
                                        .addComponent(textfieldCorreoAE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtClaveAE)
                                        .addComponent(txtConfirmarClaveAE)
                                        .addComponent(textfieldClaveAE)
                                        .addComponent(textfieldConfirmarClaveAE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCargoaCuplirAE)
                                        .addComponent(cargoaCumplirComboBoxAE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonBorrarAE))
                                .addComponent(textfieldDireccionAE, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtregistrodeEmpleadoAE)
                    .addComponent(botonVolverAE))
                .addGap(2, 2, 2)
                .addComponent(barraTituloAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCargoaCuplirAE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargoaCumplirComboBoxAE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPrimerNombreAE)
                                    .addComponent(txtCedulaAE)
                                    .addComponent(txtClaveAE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textfieldPrimerNombreAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfieldCedulaAE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfieldClaveAE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSegundoNombreAE)
                                    .addComponent(txtCorreoAE)
                                    .addComponent(txtConfirmarClaveAE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textfieldSegundoNombreAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfieldCorreoAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfieldConfirmarClaveAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefonoAE)
                                    .addComponent(txtPrimerApellidoAE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textfieldPrimerApellidoAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfieldTelefonoAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(botonBorrarAE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSegundoApellidoAE)
                    .addComponent(txtDireccionAE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfieldDireccionAE, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldSegundoApellidoAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonGuardarAE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldSegundoNombreAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldSegundoNombreAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldSegundoNombreAEActionPerformed

    private void textfieldSegundoApellidoAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldSegundoApellidoAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldSegundoApellidoAEActionPerformed

    private void textfieldDireccionAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldDireccionAEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldDireccionAEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraTituloAE;
    private javax.swing.JLabel botonBorrarAE;
    private javax.swing.JButton botonGuardarAE;
    private javax.swing.JLabel botonVolverAE;
    private javax.swing.JComboBox<String> cargoaCumplirComboBoxAE;
    private javax.swing.JTextField textfieldCedulaAE;
    private javax.swing.JTextField textfieldClaveAE;
    private javax.swing.JTextField textfieldConfirmarClaveAE;
    private javax.swing.JTextField textfieldCorreoAE;
    private javax.swing.JTextField textfieldDireccionAE;
    private javax.swing.JTextField textfieldPrimerApellidoAE;
    private javax.swing.JTextField textfieldPrimerNombreAE;
    private javax.swing.JTextField textfieldSegundoApellidoAE;
    private javax.swing.JTextField textfieldSegundoNombreAE;
    private javax.swing.JTextField textfieldTelefonoAE;
    private javax.swing.JLabel txtCargoaCuplirAE;
    private javax.swing.JLabel txtCedulaAE;
    private javax.swing.JLabel txtClaveAE;
    private javax.swing.JLabel txtConfirmarClaveAE;
    private javax.swing.JLabel txtCorreoAE;
    private javax.swing.JLabel txtDireccionAE;
    private javax.swing.JLabel txtPrimerApellidoAE;
    private javax.swing.JLabel txtPrimerNombreAE;
    private javax.swing.JLabel txtSegundoApellidoAE;
    private javax.swing.JLabel txtSegundoNombreAE;
    private javax.swing.JLabel txtTelefonoAE;
    private javax.swing.JLabel txtregistrodeEmpleadoAE;
    // End of variables declaration//GEN-END:variables
}
