/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package expoferia.pagos.gestionpagos.gui.formularios;

import com.toedter.calendar.JDateChooser;
import expoferia.pagos.gestionpagos.dao.EmpleadoDAO;
import expoferia.pagos.gestionpagos.entidades.Empleado;
import expoferia.pagos.gestionpagos.gui.SistemaAdmin;
import expoferia.pagos.gestionpagos.gui.modulos.PanelDefault;
import expoferia.pagos.gestionpagos.util.Password;

import javax.swing.*;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Arrays;

/**
 *
 * @author USER
 */
public class RegistroEmpleados extends javax.swing.JPanel {

    JDateChooser dateChooser;
    Empleado empleado;
    /**
     * Creates new form RegistroEmpleados
     */
    public RegistroEmpleados() {
        initComponents();

        dateChooser = new JDateChooser();

        SimpleDateFormat spf=new SimpleDateFormat("yyyy/MM/dd");
        try {
            java.util.Date fechaMinR= spf.parse("1960/01/01");
            java.util.Date fechaMaxR= spf.parse("2007/01/01");
            dateChooser.setDateFormatString("yyyy/MM/dd");
            dateChooser.setMinSelectableDate(fechaMinR);
            dateChooser.setMaxSelectableDate(fechaMaxR);
            dateChooser.setDate(fechaMaxR);

        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        panelCalendario.add(dateChooser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        botonVolverRE = new javax.swing.JLabel();
        txtregistrodeEmpleadoRE = new javax.swing.JLabel();
        botonBorrarRE = new javax.swing.JLabel();
        txtClaveRE = new javax.swing.JLabel();
        textfieldPrimerNombreRE = new javax.swing.JTextField();
        txtPrimerNombreRE = new javax.swing.JLabel();
        txtCedula = new javax.swing.JLabel();
        textfieldCedulaRE = new javax.swing.JTextField();
        txtSegundoNombreRE = new javax.swing.JLabel();
        textfieldSegundoNombreRE = new javax.swing.JTextField();
        txtPrimerApellidoRE = new javax.swing.JLabel();
        txtSegundoApellidoRE = new javax.swing.JLabel();
        textfieldPrimerApellidoRE = new javax.swing.JTextField();
        textfieldSegundoApellidoRE = new javax.swing.JTextField();
        comboBoxCargoaCumplirRE = new javax.swing.JComboBox<>();
        txtCargoaCumplirRE = new javax.swing.JLabel();
        textfieldTelefonoRE = new javax.swing.JTextField();
        txtTelefonoRE = new javax.swing.JLabel();
        txtConfirmarClaveRE = new javax.swing.JLabel();
        txtDireccionRE = new javax.swing.JLabel();
        textfieldDireccionRE = new javax.swing.JTextField();
        botonGuardarRE = new javax.swing.JButton();
        panelCalendario = new javax.swing.JPanel();
        txtDireccionRE1 = new javax.swing.JLabel();
        confirmarPassword = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        textfieldCorreoRE = new javax.swing.JTextField();
        txtDireccionRE2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2.setPreferredSize(new java.awt.Dimension(2, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        botonVolverRE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/retroceder.png"))); // NOI18N
        botonVolverRE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVolverRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonVolverREMouseClicked(evt);
            }
        });

        txtregistrodeEmpleadoRE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtregistrodeEmpleadoRE.setForeground(new java.awt.Color(10, 72, 162));
        txtregistrodeEmpleadoRE.setText("REGISTRO DE EMPLEADOS");

        botonBorrarRE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        botonBorrarRE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBorrarRE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonBorrarREMouseClicked(evt);
            }
        });

        txtClaveRE.setForeground(new java.awt.Color(0, 0, 0));
        txtClaveRE.setText("Contraseña");

        textfieldPrimerNombreRE.setBackground(new java.awt.Color(255, 255, 255));
        textfieldPrimerNombreRE.setForeground(new java.awt.Color(0, 0, 0));
        textfieldPrimerNombreRE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        txtPrimerNombreRE.setForeground(new java.awt.Color(0, 0, 0));
        txtPrimerNombreRE.setText("Primer Nombre");

        txtCedula.setForeground(new java.awt.Color(0, 0, 0));
        txtCedula.setText("Cedula");

        textfieldCedulaRE.setBackground(new java.awt.Color(255, 255, 255));
        textfieldCedulaRE.setForeground(new java.awt.Color(0, 0, 0));
        textfieldCedulaRE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        txtSegundoNombreRE.setForeground(new java.awt.Color(0, 0, 0));
        txtSegundoNombreRE.setText("Segundo Nombre");

        textfieldSegundoNombreRE.setBackground(new java.awt.Color(255, 255, 255));
        textfieldSegundoNombreRE.setForeground(new java.awt.Color(0, 0, 0));
        textfieldSegundoNombreRE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        textfieldSegundoNombreRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldSegundoNombreREActionPerformed(evt);
            }
        });

        txtPrimerApellidoRE.setForeground(new java.awt.Color(0, 0, 0));
        txtPrimerApellidoRE.setText("Primer Apellido");

        txtSegundoApellidoRE.setForeground(new java.awt.Color(0, 0, 0));
        txtSegundoApellidoRE.setText("Segundo Apellido");

        textfieldPrimerApellidoRE.setBackground(new java.awt.Color(255, 255, 255));
        textfieldPrimerApellidoRE.setForeground(new java.awt.Color(0, 0, 0));
        textfieldPrimerApellidoRE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        textfieldSegundoApellidoRE.setBackground(new java.awt.Color(255, 255, 255));
        textfieldSegundoApellidoRE.setForeground(new java.awt.Color(0, 0, 0));
        textfieldSegundoApellidoRE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        textfieldSegundoApellidoRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldSegundoApellidoREActionPerformed(evt);
            }
        });

        comboBoxCargoaCumplirRE.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxCargoaCumplirRE.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxCargoaCumplirRE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un cargo", "Administrador", "Cajero" }));
        comboBoxCargoaCumplirRE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        comboBoxCargoaCumplirRE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtCargoaCumplirRE.setForeground(new java.awt.Color(0, 0, 0));
        txtCargoaCumplirRE.setText("Cargo");

        textfieldTelefonoRE.setBackground(new java.awt.Color(255, 255, 255));
        textfieldTelefonoRE.setForeground(new java.awt.Color(0, 0, 0));
        textfieldTelefonoRE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        txtTelefonoRE.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoRE.setText("Telefono");

        txtConfirmarClaveRE.setForeground(new java.awt.Color(0, 0, 0));
        txtConfirmarClaveRE.setText("Confirmar Contraseña");

        txtDireccionRE.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccionRE.setText("Dirección");

        textfieldDireccionRE.setBackground(new java.awt.Color(255, 255, 255));
        textfieldDireccionRE.setForeground(new java.awt.Color(0, 0, 0));
        textfieldDireccionRE.setActionCommand("<Not Set>");
        textfieldDireccionRE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        textfieldDireccionRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldDireccionREActionPerformed(evt);
            }
        });

        botonGuardarRE.setBackground(new java.awt.Color(3, 105, 173));
        botonGuardarRE.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarRE.setText("Guardar");
        botonGuardarRE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardarRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarREActionPerformed(evt);
            }
        });

        panelCalendario.setBackground(new java.awt.Color(255, 255, 255));
        panelCalendario.setLayout(new java.awt.BorderLayout());

        txtDireccionRE1.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccionRE1.setText("Fecha de Nacimiento");

        confirmarPassword.setBackground(new java.awt.Color(255, 255, 255));
        confirmarPassword.setForeground(new java.awt.Color(0, 0, 0));
        confirmarPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        textfieldCorreoRE.setBackground(new java.awt.Color(255, 255, 255));
        textfieldCorreoRE.setForeground(new java.awt.Color(0, 0, 0));
        textfieldCorreoRE.setActionCommand("<Not Set>");
        textfieldCorreoRE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        textfieldCorreoRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldCorreoREActionPerformed(evt);
            }
        });

        txtDireccionRE2.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccionRE2.setText("Correo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonVolverRE)
                                .addGap(18, 18, 18)
                                .addComponent(txtregistrodeEmpleadoRE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldPrimerApellidoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrimerApellidoRE)
                                    .addComponent(textfieldSegundoNombreRE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSegundoNombreRE)
                                    .addComponent(textfieldPrimerNombreRE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrimerNombreRE))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDireccionRE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldDireccionRE, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtTelefonoRE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldTelefonoRE, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldCedulaRE, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSegundoApellidoRE)
                                    .addComponent(textfieldSegundoApellidoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panelCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                    .addComponent(txtDireccionRE1))
                                .addGap(104, 104, 104)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionRE2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textfieldCorreoRE)
                                    .addComponent(txtClaveRE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtConfirmarClaveRE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCargoaCumplirRE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxCargoaCumplirRE, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                                    .addComponent(confirmarPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addComponent(botonBorrarRE)))))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(botonGuardarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtregistrodeEmpleadoRE)
                    .addComponent(botonVolverRE))
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCargoaCumplirRE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxCargoaCumplirRE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPrimerNombreRE)
                                .addComponent(txtClaveRE))
                            .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textfieldPrimerNombreRE)
                                .addComponent(textfieldCedulaRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonBorrarRE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtConfirmarClaveRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldSegundoNombreRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrimerApellidoRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldPrimerApellidoRE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefonoRE)
                                    .addComponent(txtSegundoNombreRE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldTelefonoRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtDireccionRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldDireccionRE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccionRE1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSegundoApellidoRE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textfieldSegundoApellidoRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDireccionRE2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldCorreoRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(botonGuardarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textfieldSegundoApellidoREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldSegundoApellidoREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldSegundoApellidoREActionPerformed

    private void textfieldDireccionREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldDireccionREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldDireccionREActionPerformed

    private void textfieldSegundoNombreREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldSegundoNombreREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldSegundoNombreREActionPerformed

    private void botonGuardarREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarREActionPerformed
        guardar();
    }//GEN-LAST:event_botonGuardarREActionPerformed

    private void botonBorrarREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBorrarREMouseClicked
        refrescarEmpleado();
    }//GEN-LAST:event_botonBorrarREMouseClicked

    private void botonVolverREMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverREMouseClicked
        SistemaAdmin.card.show(SistemaAdmin.panelCambiante, PanelDefault.Titulo);
        SistemaAdmin.panelCambiante.revalidate();
        SistemaAdmin.panelCambiante.repaint();
    }//GEN-LAST:event_botonVolverREMouseClicked

    private void textfieldCorreoREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldCorreoREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldCorreoREActionPerformed

    public void refrescarEmpleado() {

        int confirmacion = JOptionPane.showConfirmDialog(null,
                "¿Seguro que desea limpiar los campos de empleado?", "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion==0) {
            textfieldCedulaRE.setText("");
            textfieldPrimerNombreRE.setText("");
            textfieldSegundoNombreRE.setText("");
            textfieldPrimerApellidoRE.setText("");
            textfieldSegundoApellidoRE.setText("");
            textfieldTelefonoRE.setText("");
            textfieldCorreoRE.setText("");
            textfieldDireccionRE.setText("");
            password.setText("");
            confirmarPassword.setText("");
            comboBoxCargoaCumplirRE.setSelectedItem(0);
            SimpleDateFormat spf=new SimpleDateFormat("yyyy/MM/dd");
            try {
                java.util.Date fechaMaxR= spf.parse("2007/01/01");
                dateChooser.setDate(fechaMaxR);
            } catch (ParseException e) {
                throw new RuntimeException(e);
            }
        }

    }

    public boolean validarCampos() {

        String cedula = textfieldCedulaRE.getText().trim();
        String nombre1 = textfieldPrimerNombreRE.getText();
        String nombre2 = textfieldSegundoNombreRE.getText();
        String apellido1 = textfieldPrimerApellidoRE.getText();
        String apellido2 = textfieldSegundoApellidoRE.getText();
        String telefono = textfieldTelefonoRE.getText();
        String correo = textfieldCorreoRE.getText();
        String direccion = textfieldDireccionRE.getText();
        String contra = new String(password.getPassword());
        String contra2 = new String(confirmarPassword.getPassword());
        String cargo = comboBoxCargoaCumplirRE.getSelectedItem().toString();

        if (cedula.isBlank() || nombre1.isBlank() || nombre2.isBlank() || apellido1.isBlank() ||
            apellido2.isBlank() || telefono.isBlank() || correo.isBlank() || direccion.isBlank() ||
            contra.isBlank() || contra2.isBlank()) {
            JOptionPane.showMessageDialog(null, "Los campos no pueden quedar vacíos o con espacios en blanco.");
            return false;
        }

        if (!cedula.matches("^V\\d+")) {
            JOptionPane.showMessageDialog(null, "La cédula solo debe contener V y números.");
            return false;
        }

        String regex = "[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+";
        if (!nombre1.matches(regex) || !nombre2.matches(regex) ||
            !apellido1.matches(regex) || !apellido2.matches(regex)) {
            JOptionPane.showMessageDialog(null, "Los nombres y apellidos solo deben contener letras.");
            return false;
        }

        if (!telefono.matches("\\d{11}")) {
            JOptionPane.showMessageDialog(null, "El número de teléfono debe tener exactamente 11 dígitos numéricos.");
            return false;
        }

        if (!correo.matches("^[a-zA-Z0-9._%+-]+@gonzaga\\.edu\\.ve$")) {
            JOptionPane.showMessageDialog(null, "El correo debe pertenecer al dominio @gonzaga.edu.ve");
            return false;
        }

        if (!direccion.matches("^[\\p{L}\\d\\s,#.-]+$")) {
            JOptionPane.showMessageDialog(null, "El número de teléfono debe tener exactamente 11 dígitos numéricos.");
            return false;
        }

        if (!contra.equals(contra2)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
            return false;
        }

        if (cargo.equals("Elige un cargo")) {
            JOptionPane.showMessageDialog(null, "Debe de seleccionar un cargo.");
            return false;
        }

        return true;

    }

    public void guardar() {

        if (validarCampos()) {

            int confirmacion = JOptionPane.showConfirmDialog(null,
                    "¿Seguro que desea registrar al empleado?", "Confirmación",
                    JOptionPane.YES_NO_OPTION);

            if (confirmacion==0) {

                EmpleadoDAO eDao=new EmpleadoDAO();
                guardarDatos();
                boolean exito=eDao.agregar(empleado);

                if (exito) {
                    JOptionPane.showMessageDialog(null, "Empleado registrado éxitosamente.");
                } else JOptionPane.showMessageDialog(null, "Ocurrió un error al registrar el empleado.");

            }

        }

    }

    public void guardarDatos() {

        empleado=new Empleado();
        empleado.setCedula(textfieldCedulaRE.getText().trim());
        empleado.setNombre1(textfieldPrimerNombreRE.getText().trim());
        empleado.setNombre2(textfieldSegundoNombreRE.getText().trim());
        empleado.setApellido1(textfieldPrimerApellidoRE.getText().trim());
        empleado.setApellido2(textfieldSegundoApellidoRE.getText().trim());
        empleado.setCorreo(textfieldCorreoRE.getText().trim());
        empleado.setTelefono(textfieldTelefonoRE.getText().trim());
        empleado.setDireccion(textfieldDireccionRE.getText().trim());

        java.util.Date utilFecha = dateChooser.getDate();
        java.sql.Date sqlFecha = new java.sql.Date(utilFecha.getTime());
        empleado.setFechaN((sqlFecha));

        empleado.setEstado(true);
        if (comboBoxCargoaCumplirRE.getSelectedItem().equals("Administrador")) empleado.setRol(true);
        else empleado.setRol(false);
        empleado.setContrasena(Password.hashContrasena(new String(password.getPassword())));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonBorrarRE;
    private javax.swing.JButton botonGuardarRE;
    private javax.swing.JLabel botonVolverRE;
    private javax.swing.JComboBox<String> comboBoxCargoaCumplirRE;
    private javax.swing.JPasswordField confirmarPassword;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelCalendario;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField textfieldCedulaRE;
    private javax.swing.JTextField textfieldCorreoRE;
    private javax.swing.JTextField textfieldDireccionRE;
    private javax.swing.JTextField textfieldPrimerApellidoRE;
    private javax.swing.JTextField textfieldPrimerNombreRE;
    private javax.swing.JTextField textfieldSegundoApellidoRE;
    private javax.swing.JTextField textfieldSegundoNombreRE;
    private javax.swing.JTextField textfieldTelefonoRE;
    private javax.swing.JLabel txtCargoaCumplirRE;
    private javax.swing.JLabel txtCedula;
    private javax.swing.JLabel txtClaveRE;
    private javax.swing.JLabel txtConfirmarClaveRE;
    private javax.swing.JLabel txtDireccionRE;
    private javax.swing.JLabel txtDireccionRE1;
    private javax.swing.JLabel txtDireccionRE2;
    private javax.swing.JLabel txtPrimerApellidoRE;
    private javax.swing.JLabel txtPrimerNombreRE;
    private javax.swing.JLabel txtSegundoApellidoRE;
    private javax.swing.JLabel txtSegundoNombreRE;
    private javax.swing.JLabel txtTelefonoRE;
    private javax.swing.JLabel txtregistrodeEmpleadoRE;
    // End of variables declaration//GEN-END:variables
}
